### ISSUE TITLE
Cool repo

### ISSUE THREAD

**Issue by KcrPL** [MikeModder/Amazing-IOS-Patcher-That-Is-Better-Than-KcrPLs#1]
![](http://i.imgur.com/kIHJW0v.gif)

**Comment by MikeModder** [comment]
I will crush you :P

YOU WILL BE REPLACED!

**Comment by KcrPL** [comment]
i've spent a lot of time on it
don't do it please

**Comment by larsenv** [comment]
Why MikeModder? We don't need a GUI.

Don't waste your time.

**Comment by MikeModder** [comment]
¯\_(ツ)_/¯ I'm too bored to care at this point
